name: Build base images

on:
  push:
    branches:
      - 'main'
      - 'test_build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push remote
      uses: docker/bake-action@v5
      with:
        push: true
        set: |
          *.platform=linux/amd64,linux/arm64
          cli.tags=ghcr.io/${{ github.repository_owner }}/drupal-base-image/cli:latest
          nginx.tags=ghcr.io/${{ github.repository_owner }}/drupal-base-image/nginx:latest
          php.tags=ghcr.io/${{ github.repository_owner }}/drupal-base-image/php:latest

    - name: Tag Docker images
      run: |
        docker tag drupal-base-cli:latest uselagoon/drupal-base-image-cli:latest
        docker tag drupal-base-php:latest uselagoon/drupal-base-image-php:latest
        docker tag drupal-base-nginx:latest uselagoon/drupal-base-image-nginx:latest

    - name: List images
      run: docker image ls

    - name: Build and push local
      uses: docker/bake-action@v5
      with:
        load: true
        set: |
          *.platform=linux/amd64
          cli.tags=drupal-base-cli:latest
          nginx.tags=drupal-base-nginx:latest
          php.tags=drupal-base-php:latest

    - name: List images
      run: docker image ls
