name: Build base images

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build drupal-base-cli image
    #   run: docker build -t uselagoon/drupal-base-cli:latest -t drupal-base-cli -f ./lagoon/cli.dockerfile .

    # - name: Build drupal-base-nginx image
    #   run: docker build -t uselagoon/drupal-base-nginx:latest -f ./lagoon/nginx.dockerfile .

    # - name: Build drupal-base-php image
    #   run: docker build -t uselagoon/drupal-base-php:latest -f ./lagoon/php.dockerfile .

    - name: Build Docker images
      run: docker compose -f docker-compose.yml build

    - name: List images
      run: docker image ls

    # - name: Tag Docker images
    #   run: |
    #     docker tag your-dockerhub-username/your-app:latest your-dockerhub-username/your-app:main
    #     docker tag your-dockerhub-username/your-app:latest ghcr.io/your-github-username/your-app:latest

    # - name: Push Docker images to Docker Hub
    #   run: |
    #     docker push your-dockerhub-username/your-app:latest
    #     docker push your-dockerhub-username/your-app:main

    # - name: Push Docker images to GitHub Container Registry
    #   run: docker push ghcr.io/your-github-username/your-app:latest